### PR TITLE
(chore): Refactor id validation

### PR DESCRIPTION
**Pull request by Ijebusoma**

### CODE REVIEW

**Comment by solutionstack** [comment]
Hi, i'd be dropping hints on various commits or files as much as I can.

So first of all, a few things, maybe you did them intentionally

- Validation: you are not validating data from req.body, req.params etc, so you'd get errors when trying to access values which wasn't sent by he clients

**Comment by solutionstack** [comment]
- Work on avoiding code repetition
   e.g every controller method has the error block 
 `res.status(500).json({
          errors: {
            status: '500',
            detail: 'Internal server error',
          },
        });`

This feature can be offloaded to a utility package that'll be imported by all controllers, so you could have say a `utility.handleErrors` function, which would handle errors emanating from your controllers

Other cases are text scattered around the controller  `e.g` appears twice in the user-controller
you could have such texts defined in a constants.js file, and just reference them when needed

**Comment by solutionstack** [comment]
I think the pattern used in your `routes` file is pretty cool btw

**Comment by wrillrysata** [comment]
Just seeing this. Thanks a lot @solutionstack . Would work on improving on those, thanks

**Comment by solutionstack** [comment]
You could look into any of the following for your validation needs

-  Express Validator (https://express-validator.github.io/docs/)

- Joi (https://github.com/hapijs/joi)

**Pull request merged**
